import type { Metadata, Viewport } from "next";
import "./globals.css";
import { StoreProvider } from "@/lib/state";
import { safeJsonLd } from "@/lib/jsonLd";
import { TopBar } from "@/components/TopBar";
import { OveruseNudge } from "@/components/OveruseNudge";
import { Onboarding } from "@/components/Onboarding";
import { Toaster } from "@/components/Toaster";
import { KeyboardShortcuts } from "@/components/KeyboardShortcuts";
import { BottomNav } from "@/components/BottomNav";
import { CommandPalette } from "@/components/CommandPalette";
import { ServiceWorkerRegister } from "@/components/ServiceWorkerRegister";
import { Coachmarks } from "@/components/Coachmarks";
import { Footer } from "@/components/Footer";
import { ScrollTopFab } from "@/components/ScrollTopFab";
import { RouteAnnouncer } from "@/components/RouteAnnouncer";

const SITE = "https://polymath.vercel.app";

export const metadata: Metadata = {
 metadataBase: new URL(SITE),
 title: {
  default: "Polymath. Learn anything, daily.",
  template: "%s · Polymath"
 },
 description:
  "Learn dozens of real-world domains from absolute basics to mastery. Spaced repetition, real missions, real frameworks, honest game loop. No login, no dark patterns.",
 applicationName: "Polymath",
 keywords: [
  "spaced repetition", "FSRS", "learning app", "polymath",
  "mental models", "personal finance", "marketing", "AI",
  "concept quizzes", "epistemic honesty", "real-world missions"
 ],
 authors: [{ name: "Polymath" }],
 creator: "Polymath",
 publisher: "Polymath",
 manifest: "/manifest.webmanifest",
 alternates: { canonical: "/" },
 robots: {
  index: true,
  follow: true,
  googleBot: { index: true, follow: true, "max-snippet": -1, "max-image-preview": "large" }
 },
 openGraph: {
  type: "website",
  siteName: "Polymath",
  title: "Polymath. Learn anything, daily.",
  description: "A daily learning loop for real-world domains. FSRS spaced repetition. Honest game loop.",
  url: SITE,
  locale: "en_US"
 },
 twitter: {
  card: "summary_large_image",
  title: "Polymath",
  description: "Learn anything, daily. FSRS spaced repetition, real frameworks, no dark patterns."
 },
 category: "education"
};

export const viewport: Viewport = {
 themeColor: [
  { media: "(prefers-color-scheme: dark)",  color: "#0b0d1a" },
  { media: "(prefers-color-scheme: light)", color: "#f7f7fb" }
 ],
 width: "device-width",
 initialScale: 1,
 maximumScale: 5,
 colorScheme: "dark light"
};

// JSON-LD structured data. Helps search engines understand this is an
// educational application with a catalogue of learning resources.
const jsonLd = {
 "@context": "https://schema.org",
 "@type": "WebApplication",
 name: "Polymath",
 applicationCategory: "EducationalApplication",
 operatingSystem: "Web",
 url: SITE,
 description:
  "A daily learning loop for real-world domains. Spaced repetition, real missions, real frameworks, honest game loop. No login, no dark patterns.",
 offers: { "@type": "Offer", price: "0", priceCurrency: "USD" },
 isAccessibleForFree: true,
 inLanguage: "en"
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
 return (
  <html lang="en" suppressHydrationWarning>
   <head>
    {/* Favicon + apple-touch-icon are generated by app/icon.tsx and
        app/apple-icon.tsx — Next.js wires the <link> tags automatically. */}
    <link rel="alternate" type="application/rss+xml" title="Polymath domains" href="/domains.rss" />
    <script
     type="application/ld+json"
     dangerouslySetInnerHTML={{ __html: safeJsonLd(jsonLd) }}
    />
   </head>
   <body>
    <StoreProvider>
     <a href="#main" className="sr-only focus:not-sr-only focus:fixed focus:top-2 focus:left-2 focus:z-50 focus:btn">Skip to content</a>
     <TopBar />
     <main id="main" className="mx-auto max-w-6xl px-4 py-6 pb-24 sm:pb-6">{children}</main>
     <OveruseNudge />
     <Onboarding />
     <Toaster />
     <KeyboardShortcuts />
     <CommandPalette />
     <ServiceWorkerRegister />
     <Coachmarks />
     <BottomNav />
     <ScrollTopFab />
     <RouteAnnouncer />
     <Footer />
    </StoreProvider>
   </body>
  </html>
 );
}
